tacmd histstartcollection -a "CICSplex AID Analysis                      " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Application Bundle Detail         " -m "*MVS_CICS"  
tacmd histstartcollection -a "CICSplex Application Bundle Parts          " -m "*MVS_CICS"  
tacmd histstartcollection -a "CICSplex Application Bundle Summary        " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Atom Feed Detail                  " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Atom Feed Summary                 " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Auxiliary Temporary Storage Details" -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Bottleneck Analysis               " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex BTS Activity Details              " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex BTS Container Details             " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex BTS Process Details               " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex BTS ProcessType Details           " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Connection Analysis               " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Connections Summary               " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Corbaserver Summary               " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex DB2 Summary                       " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex DB2 Task Activity                 " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex DBCTL Summary                     " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Dispatcher Summary                " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Dispatcher TCB Modes              " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Dispatcher TCB Pools              " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex DJAR Details                      " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Document template details         " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Dump Analysis                     " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Dump Details                      " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Dynamic Storage Details           " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Enqueue Analysis                  " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Enqueue Pool Details              " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Enterprise Java Bean Details      " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Event Processing Details          " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Event Processing Summary          " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Exit Program Analysis             " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex File Control Analysis             " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex File Control Summary              " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex ICE Analysis                      " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Intercommunication Summary        " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Internet Status                   " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex IPConnection Analysis             " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Java Program Analysis             " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Journal Analysis                  " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex JVM Analysis                      " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex JVM Classcache Details            " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex JVM Server Analysis               " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex JVMPOOL Statistics                " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex JVMProfile Analysis               " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Log Stream Analysis               " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex LSR Pool Status                   " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex MQ Connection Details             " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex MVS TCB GLOBAL details            " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex MVS TCB RESOURCE details          " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Overview                          " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Pagepool Details                  " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Pagepool Summary                  " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Pipeline Summary                  " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Plex Service Class Analysis       " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Recovery Manager Details          " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Region Dataset Analysis           " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Region Overview                   " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Request Model Summary             " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Response Time Analysis            " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Response Time Elements            " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex RLS Lock Analysis                 " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Service Class Analysis            " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Storage Analysis                  " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Subpool Details                   " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex System Initialization Table       " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Task Class Analysis               " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex TCPIP Service Statistics          " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex TCPIP Statistics                  " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Temporary Storage Detail          " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Temporary Storage Details         " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Temporary Storage Extended        " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Temporary Storage Summary         " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Terminal Storage Violations       " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Transaction Analysis              " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Transaction Application Program   " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Transaction Definition Information" -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Transaction Details               " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Transaction EIB Detail            " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Transaction EIB Summary           " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Transaction File Details          " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Transaction I/O Waits Analysis    " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Transaction Manager Statistics    " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Transaction Remote Information    " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Transaction Statistics            " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Transaction Storage Analysis      " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Transaction Storage Violations    " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Transaction Timings               " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Transaction TSQUEUE Details       " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Transaction Umbrella Data         " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Transaction Wait Other Analysis   " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Transient Data Queues             " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Transient Data Summary            " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Unit-of-work DSN Failure Details  " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Unit-of-work Link Details         " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex UOW Analysis                      " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex UOW Enqueue Analysis              " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex URIMAP Global                     " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex URIMAP Summary                    " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Virtual Host Detail               " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex VSAM Analysis                     " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Web Service Summary               " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex Workrequest Details               " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex XML Detail                        " -m "*MVS_CICS" 
tacmd histstartcollection -a "CICSplex XML Summary                       " -m "*MVS_CICS"
