tacmd histdeletecollection -a "CICSplex AID Analysis                      " 
tacmd histdeletecollection -a "CICSplex Application Bundle Detail         "  
tacmd histdeletecollection -a "CICSplex Application Bundle Parts          "  
tacmd histdeletecollection -a "CICSplex Application Bundle Summary        " 
tacmd histdeletecollection -a "CICSplex Atom Feed Detail                  " 
tacmd histdeletecollection -a "CICSplex Atom Feed Summary                 " 
tacmd histdeletecollection -a "CICSplex Auxiliary Temporary Storage Details" 
tacmd histdeletecollection -a "CICSplex Bottleneck Analysis               " 
tacmd histdeletecollection -a "CICSplex BTS Activity Details              " 
tacmd histdeletecollection -a "CICSplex BTS Container Details             " 
tacmd histdeletecollection -a "CICSplex BTS Process Details               " 
tacmd histdeletecollection -a "CICSplex BTS ProcessType Details           " 
tacmd histdeletecollection -a "CICSplex Connection Analysis               " 
tacmd histdeletecollection -a "CICSplex Connections Summary               " 
tacmd histdeletecollection -a "CICSplex Corbaserver Summary               " 
tacmd histdeletecollection -a "CICSplex DB2 Summary                       " 
tacmd histdeletecollection -a "CICSplex DB2 Task Activity                 " 
tacmd histdeletecollection -a "CICSplex DBCTL Summary                     " 
tacmd histdeletecollection -a "CICSplex Dispatcher Summary                " 
tacmd histdeletecollection -a "CICSplex Dispatcher TCB Modes              " 
tacmd histdeletecollection -a "CICSplex Dispatcher TCB Pools              " 
tacmd histdeletecollection -a "CICSplex DJAR Details                      " 
tacmd histdeletecollection -a "CICSplex Document template details         " 
tacmd histdeletecollection -a "CICSplex Dump Analysis                     " 
tacmd histdeletecollection -a "CICSplex Dump Details                      " 
tacmd histdeletecollection -a "CICSplex Dynamic Storage Details           " 
tacmd histdeletecollection -a "CICSplex Enqueue Analysis                  " 
tacmd histdeletecollection -a "CICSplex Enqueue Pool Details              " 
tacmd histdeletecollection -a "CICSplex Enterprise Java Bean Details      " 
tacmd histdeletecollection -a "CICSplex Event Processing Details          " 
tacmd histdeletecollection -a "CICSplex Event Processing Summary          " 
tacmd histdeletecollection -a "CICSplex Exit Program Analysis             " 
tacmd histdeletecollection -a "CICSplex File Control Analysis             " 
tacmd histdeletecollection -a "CICSplex File Control Summary              " 
tacmd histdeletecollection -a "CICSplex ICE Analysis                      " 
tacmd histdeletecollection -a "CICSplex Intercommunication Summary        " 
tacmd histdeletecollection -a "CICSplex Internet Status                   " 
tacmd histdeletecollection -a "CICSplex IPConnection Analysis             " 
tacmd histdeletecollection -a "CICSplex Java Program Analysis             " 
tacmd histdeletecollection -a "CICSplex Journal Analysis                  " 
tacmd histdeletecollection -a "CICSplex JVM Analysis                      " 
tacmd histdeletecollection -a "CICSplex JVM Classcache Details            " 
tacmd histdeletecollection -a "CICSplex JVM Server Analysis               " 
tacmd histdeletecollection -a "CICSplex JVMPOOL Statistics                " 
tacmd histdeletecollection -a "CICSplex JVMProfile Analysis               " 
tacmd histdeletecollection -a "CICSplex Log Stream Analysis               " 
tacmd histdeletecollection -a "CICSplex LSR Pool Status                   " 
tacmd histdeletecollection -a "CICSplex MQ Connection Details             " 
tacmd histdeletecollection -a "CICSplex MVS TCB GLOBAL details            " 
tacmd histdeletecollection -a "CICSplex MVS TCB RESOURCE details          " 
tacmd histdeletecollection -a "CICSplex Overview                          " 
tacmd histdeletecollection -a "CICSplex Pagepool Details                  " 
tacmd histdeletecollection -a "CICSplex Pagepool Summary                  " 
tacmd histdeletecollection -a "CICSplex Pipeline Summary                  " 
tacmd histdeletecollection -a "CICSplex Plex Service Class Analysis       " 
tacmd histdeletecollection -a "CICSplex Recovery Manager Details          " 
tacmd histdeletecollection -a "CICSplex Region Dataset Analysis           " 
tacmd histdeletecollection -a "CICSplex Region Overview                   " 
tacmd histdeletecollection -a "CICSplex Request Model Summary             " 
tacmd histdeletecollection -a "CICSplex Response Time Analysis            " 
tacmd histdeletecollection -a "CICSplex Response Time Elements            " 
tacmd histdeletecollection -a "CICSplex RLS Lock Analysis                 " 
tacmd histdeletecollection -a "CICSplex Service Class Analysis            " 
tacmd histdeletecollection -a "CICSplex Storage Analysis                  " 
tacmd histdeletecollection -a "CICSplex Subpool Details                   " 
tacmd histdeletecollection -a "CICSplex System Initialization Table       " 
tacmd histdeletecollection -a "CICSplex Task Class Analysis               " 
tacmd histdeletecollection -a "CICSplex TCPIP Service Statistics          " 
tacmd histdeletecollection -a "CICSplex TCPIP Statistics                  " 
tacmd histdeletecollection -a "CICSplex Temporary Storage Detail          " 
tacmd histdeletecollection -a "CICSplex Temporary Storage Details         " 
tacmd histdeletecollection -a "CICSplex Temporary Storage Extended        " 
tacmd histdeletecollection -a "CICSplex Temporary Storage Summary         " 
tacmd histdeletecollection -a "CICSplex Terminal Storage Violations       " 
tacmd histdeletecollection -a "CICSplex Transaction Analysis              " 
tacmd histdeletecollection -a "CICSplex Transaction Application Program   " 
tacmd histdeletecollection -a "CICSplex Transaction Definition Information" 
tacmd histdeletecollection -a "CICSplex Transaction Details               " 
tacmd histdeletecollection -a "CICSplex Transaction EIB Detail            " 
tacmd histdeletecollection -a "CICSplex Transaction EIB Summary           " 
tacmd histdeletecollection -a "CICSplex Transaction File Details          " 
tacmd histdeletecollection -a "CICSplex Transaction I/O Waits Analysis    " 
tacmd histdeletecollection -a "CICSplex Transaction Manager Statistics    " 
tacmd histdeletecollection -a "CICSplex Transaction Remote Information    " 
tacmd histdeletecollection -a "CICSplex Transaction Statistics            " 
tacmd histdeletecollection -a "CICSplex Transaction Storage Analysis      " 
tacmd histdeletecollection -a "CICSplex Transaction Storage Violations    " 
tacmd histdeletecollection -a "CICSplex Transaction Timings               " 
tacmd histdeletecollection -a "CICSplex Transaction TSQUEUE Details       " 
tacmd histdeletecollection -a "CICSplex Transaction Umbrella Data         " 
tacmd histdeletecollection -a "CICSplex Transaction Wait Other Analysis   " 
tacmd histdeletecollection -a "CICSplex Transient Data Queues             " 
tacmd histdeletecollection -a "CICSplex Transient Data Summary            " 
tacmd histdeletecollection -a "CICSplex Unit-of-work DSN Failure Details  " 
tacmd histdeletecollection -a "CICSplex Unit-of-work Link Details         " 
tacmd histdeletecollection -a "CICSplex UOW Analysis                      " 
tacmd histdeletecollection -a "CICSplex UOW Enqueue Analysis              " 
tacmd histdeletecollection -a "CICSplex URIMAP Global                     " 
tacmd histdeletecollection -a "CICSplex URIMAP Summary                    " 
tacmd histdeletecollection -a "CICSplex Virtual Host Detail               " 
tacmd histdeletecollection -a "CICSplex VSAM Analysis                     " 
tacmd histdeletecollection -a "CICSplex Web Service Summary               " 
tacmd histdeletecollection -a "CICSplex Workrequest Details               " 
tacmd histdeletecollection -a "CICSplex XML Detail                        " 
tacmd histdeletecollection -a "CICSplex XML Summary                       " 
