tacmd histstopcollection -a "ALL THREADS" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 CICS Exceptions" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 CICS Threads" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 CONNECT PACKAGE" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 CONNECT SERVER" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 CONNECT TASKLIST" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 DDF CONV" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 DDF STAT" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 Group Coupling Facility" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 IMS Connections" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 IMS Regions" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 Lock Conflict" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 Memory" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 Memory DBM1 DIST" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 Message" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 Parameters" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 SRM BPD" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 SRM BPM" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 SRM EDM" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 SRM EDM Statistics" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 SRM Log Manager" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 SRM Log Statistics" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 SRM Subsystem" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 SRM Subsystem Statistics" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 SRM UTL" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 System States" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 Thread Exceptions" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2 Volume Activity" -m "*MVS_DB2"  
tacmd histstopcollection -a "DB2plex Filter" -m "*MVS_DB2"  
tacmd histstopcollection -a "DISTRIBUTED THREAD DET" -m "*MVS_DB2"  
tacmd histstopcollection -a "DSG DB2 Parameters" -m "*MVS_DB2"  
tacmd histstopcollection -a "EDM POOL" -m "*MVS_DB2"  
tacmd histstopcollection -a "GBP Statistics" -m "*MVS_DB2"  
tacmd histstopcollection -a "GOA Thread Activity Summary" -m "*MVS_DB2"  
tacmd histstopcollection -a "GOA Thread Volume Summary" -m "*MVS_DB2"  
tacmd histstopcollection -a "GOA Volume Database Summary" -m "*MVS_DB2"  
tacmd histstopcollection -a "GOA Volume Summary" -m "*MVS_DB2"  
tacmd histstopcollection -a "Group" -m "*MVS_DB2"  
tacmd histstopcollection -a "Group Buffer Pool" -m "*MVS_DB2"  
tacmd histstopcollection -a "Group Buffer Pool Connection" -m "*MVS_DB2"  
tacmd histstopcollection -a "Group Object Analysis" -m "*MVS_DB2"  
tacmd histstopcollection -a "Group Object Spacename" -m "*MVS_DB2"  
tacmd histstopcollection -a "Local DB2 Lock Conflict" -m "*MVS_DB2"  
tacmd histstopcollection -a "Log Detail" -m "*MVS_DB2"  
tacmd histstopcollection -a "MVS Storage" -m "*MVS_DB2"  
tacmd histstopcollection -a "SQL COUNTER" -m "*MVS_DB2"  
tacmd histstopcollection -a "Storage Consumption" -m "*MVS_DB2"  
tacmd histstopcollection -a "THREAD DB2 CONNECT OVERVIEW" -m "*MVS_DB2"  
tacmd histstopcollection -a "THREAD DB2 CONNECT PACKAGE" -m "*MVS_DB2"  
tacmd histstopcollection -a "THREAD DB2 CONNECT SERVER" -m "*MVS_DB2"  
tacmd histstopcollection -a "THREAD DB2 CONNECT STATEMENT" -m "*MVS_DB2"  
tacmd histstopcollection -a "Thread DDF Statistics" -m "*MVS_DB2"  
tacmd histstopcollection -a "Thread Detail" -m "*MVS_DB2"  
tacmd histstopcollection -a "THREAD DETAILS" -m "*MVS_DB2"  
tacmd histstopcollection -a "THREAD ENCLAVE" -m "*MVS_DB2"  
tacmd histstopcollection -a "Thread Lock Own" -m "*MVS_DB2"  
tacmd histstopcollection -a "Thread Lock Own Summary" -m "*MVS_DB2"  
tacmd histstopcollection -a "THREAD SQL COUNTER" -m "*MVS_DB2"  
tacmd histstopcollection -a "Thread Statistics" -m "*MVS_DB2"  
tacmd histstopcollection -a "ZOS System Statistics" -m "*MVS_DB2"  
