tacmd histdeletecollection -a "ALL THREADS" 
tacmd histdeletecollection -a "DB2 CICS Exceptions" 
tacmd histdeletecollection -a "DB2 CICS Threads" 
tacmd histdeletecollection -a "DB2 CONNECT PACKAGE" 
tacmd histdeletecollection -a "DB2 CONNECT SERVER" 
tacmd histdeletecollection -a "DB2 CONNECT TASKLIST" 
tacmd histdeletecollection -a "DB2 DDF CONV" 
tacmd histdeletecollection -a "DB2 DDF STAT" 
tacmd histdeletecollection -a "DB2 Group Coupling Facility" 
tacmd histdeletecollection -a "DB2 IMS Connections" 
tacmd histdeletecollection -a "DB2 IMS Regions" 
tacmd histdeletecollection -a "DB2 Lock Conflict" 
tacmd histdeletecollection -a "DB2 Memory" 
tacmd histdeletecollection -a "DB2 Memory DBM1 DIST" 
tacmd histdeletecollection -a "DB2 Message" 
tacmd histdeletecollection -a "DB2 Parameters" 
tacmd histdeletecollection -a "DB2 SRM BPD" 
tacmd histdeletecollection -a "DB2 SRM BPM" 
tacmd histdeletecollection -a "DB2 SRM EDM" 
tacmd histdeletecollection -a "DB2 SRM EDM Statistics" 
tacmd histdeletecollection -a "DB2 SRM Log Manager" 
tacmd histdeletecollection -a "DB2 SRM Log Statistics" 
tacmd histdeletecollection -a "DB2 SRM Subsystem" 
tacmd histdeletecollection -a "DB2 SRM Subsystem Statistics" 
tacmd histdeletecollection -a "DB2 SRM UTL" 
tacmd histdeletecollection -a "DB2 System States" 
tacmd histdeletecollection -a "DB2 Thread Exceptions" 
tacmd histdeletecollection -a "DB2 Volume Activity" 
tacmd histdeletecollection -a "DB2plex Filter" 
tacmd histdeletecollection -a "DISTRIBUTED THREAD DET" 
tacmd histdeletecollection -a "DSG DB2 Parameters" 
tacmd histdeletecollection -a "EDM POOL" 
tacmd histdeletecollection -a "GBP Statistics" 
tacmd histdeletecollection -a "GOA Thread Activity Summary" 
tacmd histdeletecollection -a "GOA Thread Volume Summary" 
tacmd histdeletecollection -a "GOA Volume Database Summary" 
tacmd histdeletecollection -a "GOA Volume Summary" 
tacmd histdeletecollection -a "Group" 
tacmd histdeletecollection -a "Group Buffer Pool" 
tacmd histdeletecollection -a "Group Buffer Pool Connection" 
tacmd histdeletecollection -a "Group Object Analysis" 
tacmd histdeletecollection -a "Group Object Spacename" 
tacmd histdeletecollection -a "Local DB2 Lock Conflict" 
tacmd histdeletecollection -a "Log Detail" 
tacmd histdeletecollection -a "MVS Storage" 
tacmd histdeletecollection -a "SQL COUNTER" 
tacmd histdeletecollection -a "Storage Consumption" 
tacmd histdeletecollection -a "THREAD DB2 CONNECT OVERVIEW" 
tacmd histdeletecollection -a "THREAD DB2 CONNECT PACKAGE" 
tacmd histdeletecollection -a "THREAD DB2 CONNECT SERVER" 
tacmd histdeletecollection -a "THREAD DB2 CONNECT STATEMENT" 
tacmd histdeletecollection -a "Thread DDF Statistics" 
tacmd histdeletecollection -a "Thread Detail" 
tacmd histdeletecollection -a "THREAD DETAILS" 
tacmd histdeletecollection -a "THREAD ENCLAVE" 
tacmd histdeletecollection -a "Thread Lock Own" 
tacmd histdeletecollection -a "Thread Lock Own Summary" 
tacmd histdeletecollection -a "THREAD SQL COUNTER" 
tacmd histdeletecollection -a "Thread Statistics" 
tacmd histdeletecollection -a "ZOS System Statistics" 
