tacmd histstartcollection -a "CICSTG Active Transaction Analysis" -m "*MVS_CICSTG"
tacmd histstartcollection -a "CICSTG Active Transaction Details" -m "*MVS_CICSTG"
tacmd histstartcollection -a "CICSTG CICS TS Region Details" -m "*MVS_CICSTG"
tacmd histstartcollection -a "CICSTG CICS TS Regions" -m "*MVS_CICSTG"
tacmd histstartcollection -a "CICSTG Client Application Details" -m "*MVS_CICSTG"
tacmd histstartcollection -a "CICSTG Connection Manager Threads" -m "*MVS_CICSTG"
tacmd histstartcollection -a "CICSTG Destination Servers Details" -m "*MVS_CICSTG"
tacmd histstartcollection -a "CICSTG Gateway Daemon" -m "*MVS_CICSTG"
tacmd histstartcollection -a "CICSTG Region Overview" -m "*MVS_CICSTG"
tacmd histstartcollection -a "CICSTG Transaction Response Time Detail" -m "*MVS_CICSTG"
tacmd histstartcollection -a "CICSTG Transaction Response Time Summary" -m "*MVS_CICSTG"
tacmd histstartcollection -a "CICSTG Worker Threads" -m "*MVS_CICSTG"
