tacmd histdeletecollection -a "CICSTG Active Transaction Analysis"
tacmd histdeletecollection -a "CICSTG Active Transaction Details"
tacmd histdeletecollection -a "CICSTG CICS TS Region Details"
tacmd histdeletecollection -a "CICSTG CICS TS Regions"
tacmd histdeletecollection -a "CICSTG Client Application Details"
tacmd histdeletecollection -a "CICSTG Connection Manager Threads"
tacmd histdeletecollection -a "CICSTG Destination Servers Details"
tacmd histdeletecollection -a "CICSTG Gateway Daemon"
tacmd histdeletecollection -a "CICSTG Region Overview"
tacmd histdeletecollection -a "CICSTG Transaction Response Time Detail"
tacmd histdeletecollection -a "CICSTG Transaction Response Time Summary"
tacmd histdeletecollection -a "CICSTG Worker Threads"
