:: Use to get list of all attributes:
::   tacmd histlistattributegroups -t IP

:: Use to get all active collections
::   tacmd histlistcollections -t IP

:: Connect server
::tacmd tepslogin -s waldevompeivt01.dev.rocketsoftware.com -u sysadmin -p ''
:: Create collection
::                                                                                                                      remove (-l TEMS) to use TEMA as collection location
				
:: Start collections
::                                                                                  use (-m "IEK1:RS27:IMS" "IFK3:RS27:IMS") instead of (-m ...) to use TEMA as collection location
tacmd histstartcollection -a "Address Spaces"                                            -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Balancing Groups"                                          -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Buffer Pool Statistics"                                    -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "CF Group Name"                                             -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "DASD Logging"                                              -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Data Entry Databases"                                      -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "DBCTL Thread Calls"                                        -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "DBCTL Thread Details"                                      -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "DBCTL Thread Indoubts"                                     -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "DBCTL Thread Summaries"                                    -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Dependent Regions"                                         -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Dependent Regions Statistics"                              -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Extended Recovery Facility"                                -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "External Subsystems"                                       -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Fast Path Regions"                                         -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Fast Path System"                                          -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "HALDB Database Summary"                                    -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "HALDB Partition Detail"                                    -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "I/O Devices"                                               -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "IMS All RTA Interval Summary"                              -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "IMS All RTA Slot Summary"                                  -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "IMS Bottleneck Analysis Detail"                            -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "IMS Bottleneck Analysis Summary"                           -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "IMS Databases"                                             -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "IMS Health"                                                -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "IMS I/O"                                                   -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "IMS Local Lock Conflicts"                                  -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "IMS Local MSC Performance Statistics"                      -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "IMS Lock Conflicts"                                        -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "IMS RTA Exceptions"                                        -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "IMS RTA Group Items Slots"                                 -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "IMS RTA Groups Slots"                                      -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "IMS RTA Highest Resp Times LTERMs"                         -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "IMS RTA Highest Resp Times Trans"                          -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "IMS RTA Interval Summary"                                  -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "IMS RTA Slot Summary"                                      -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "IMS STATUS"                                                -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "IMS System"                                                -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "IMS VSAM Databases"                                        -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "IMSPLEX DBCTL Thread Summary"                              -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "IMSPLEX Health" 						 -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Internal Resource Lock Manager"                            -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Local CF IMS Data Sharing"                                 -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Local CF IMS DS OSAM"                                      -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Local IMS Startup Parameters"                              -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Local IMSCTL ACKNAK Detail"                                -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Local IMSCTL Exception Events"                             -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Local IMSCTL Resume Detail"                                -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Local IMSCTL TCPIP Usage Detail"                           -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Local IMSCTL Transit Client"                               -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Local IMSCTL Transit Detail"                               -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Local IMSCTL Transit Port"                                 -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Local IMSCTL Transit TDatastore"                           -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Local IMSCTL Transit Trancode"                             -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Local IMSCTL Transit User"                                 -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Local KIP MQ Statistics"                                   -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Local MSC Logical Links"                                   -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Local MSC Physical Links"                                  -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Local RTA GNT"                                             -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Local RTA INT"                                             -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Logical Terminals"                                         -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Main Storage Databases"                                    -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "MSDB Fields"                                               -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Omegamon XE Messages"                                      -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Online Logging Datasets"                                   -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "OSAM Subpools"                                             -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "OTMA Group"                                                -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "OTMA Status"                                               -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "OTMA TMember"                                              -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "OTMA TPipe"                                                -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Pool Buffer Statistics"                                    -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Pool Utilization"                                          -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Program Scheduling Blocks"                                 -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "RECON Datasets"                                            -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "SharedQueues APPC LUname Summary"                          -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "SharedQueues APPC TPname Summary"                          -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "SharedQueues Cold QueueName Summary"                       -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "SharedQueues Cold QueueType Summary"                       -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "SharedQueues FP Program Summary"                           -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "SharedQueues LTERM Summary"                                -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "SharedQueues OTMA Tmember Summary"                         -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "SharedQueues OTMA Tpipe Summary"                           -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "SharedQueues Transaction Summary"                          -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Sub Pool Statistics"                                       -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Subsystem Connections"                                     -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "TCBCPU Utilization"                                        -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Transaction Summary"                                       -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Transactions"                                              -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Virtual Storage Option Dataspace Areas"                    -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "Virtual Storage Option Dataspaces"                         -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "VSAM/OSAM Databases"                                       -m "*MVS_IMSPLEX"
tacmd histstartcollection -a "VSAM Subpools"                                             -m "*MVS_IMSPLEX"
