tacmd histstartcollection -a "JVM Address Space" -m "*JVM_Monitor"
tacmd histstartcollection -a "JVM CPU" -m "*JVM_Monitor"
tacmd histstartcollection -a "JVM Garbage Collection" -m "*JVM_Monitor"
tacmd histstartcollection -a "JVM Health Summary" -m "*JVM_Monitor"
tacmd histstartcollection -a "JVM Native Memory" -m "*JVM_Monitor"
tacmd histstartcollection -a "JVM Request Details" -m "*JVM_Monitor"
tacmd histstartcollection -a "JVM Request Summary" -m "*JVM_Monitor"
tacmd histstartcollection -a "JVM Virtual Memory" -m "*JVM_Monitor"
tacmd histstartcollection -a "JVM zOSConnect Summary" -m "*JVM_Monitor"
