tacmd histdeletecollection -a "JVM Address Space"
tacmd histdeletecollection -a "JVM CPU"
tacmd histdeletecollection -a "JVM Garbage Collection"
tacmd histdeletecollection -a "JVM Health Summary"
tacmd histdeletecollection -a "JVM Native Memory"
tacmd histdeletecollection -a "JVM Request Details"
tacmd histdeletecollection -a "JVM Request Summary"
tacmd histdeletecollection -a "JVM Virtual Memory"
tacmd histdeletecollection -a "JVM zOSConnect Summary"
