tacmd histstartcollection -a "Address Space ComStor Owned" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "Address Space CPU Summary History" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "Address Space CPU Utilization" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "Address Space CPU Utilization History" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "Address Space Delay Summary History" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "Address Space Real Storage" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "Address Space Summary" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "Address Space Virtual Storage" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "CF Channel Paths" -m "*MVS_SYSPLEX"
tacmd histstartcollection -a "CF Clients" -m "*MVS_SYSPLEX"
tacmd histstartcollection -a "CF Path" -m "*MVS_SYSPLEX"
tacmd histstartcollection -a "CF Policy" -m "*MVS_SYSPLEX"
tacmd histstartcollection -a "CF Structure to MVS System" -m "*MVS_SYSPLEX"
tacmd histstartcollection -a "CF Structures" -m "*MVS_SYSPLEX"
tacmd histstartcollection -a "CF Systems" -m "*MVS_SYSPLEX"
tacmd histstartcollection -a "Channel Paths" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "Common Storage" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "Common Storage Utilization History" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "CPC LPAR Details History" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "CPC LPAR Summary History" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "DASD MVS" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "DASD MVS Devices" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "Enclave Table" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "Enqueues" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "Global Enqueues" -m "*MVS_SYSPLEX"
tacmd histstartcollection -a "HiperDispatch Logical Processors" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "HiperDispatch Management" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "JES Spool Details" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "KM5 Address Space Storage SubKey" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "KM5 Common Storage SubKey" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "KM5 Device Job History" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "KM5 Device Resource History" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "KM5 Health Checks" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "KM5 License Manager MSU WLM Cap" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "KM5 MultiThreading Details" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "KM5 MultiThreading Summary" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "KM5 Spin Lock" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "KM5 Storage Details History" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "KM5 Storage Shortage Status" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "KM5 Storage Summary History" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "KM5 StorageClassMemory Details" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "KM5 StorageClassMemory Summary" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "KM5 Suspend Lock" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "KM5 zFS Directory Cache" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "KM5 zFS Kernel" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "KM5 zFS Metadata Cache" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "KM5 zFS Storage" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "KM5 zFS User Cache" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "KM5 zFS User Cache DS" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "LPAR Clusters" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "LPAR Summary History" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "Operator Alerts" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "Page Dataset Activity" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "PCIE Device Summary" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "Real Storage" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "Real Storage Utilization History" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "Report Classes" -m "*MVS_SYSPLEX"
tacmd histstartcollection -a "Resource Groups" -m "*MVS_SYSPLEX"
tacmd histstartcollection -a "SCM Device Summary" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "Service Class Address Spaces" -m "*MVS_SYSPLEX"
tacmd histstartcollection -a "Service Class Enqueue Workflow Analysis" -m "*MVS_SYSPLEX"
tacmd histstartcollection -a "Service Class I/O Workflow Analysis" -m "*MVS_SYSPLEX"
tacmd histstartcollection -a "Service Class Subsys Workflow Analysis" -m "*MVS_SYSPLEX"
tacmd histstartcollection -a "Service Definition" -m "*MVS_SYSPLEX"
tacmd histstartcollection -a "SVCDET" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "Sysplex DASD" -m "*MVS_SYSPLEX"
tacmd histstartcollection -a "Sysplex DASD Device" -m "*MVS_SYSPLEX"
tacmd histstartcollection -a "Sysplex DASD Group" -m "*MVS_SYSPLEX"
tacmd histstartcollection -a "Sysplex WLM Service Class Period" -m "*MVS_SYSPLEX"
tacmd histstartcollection -a "Sysplexes Coupling Facility" -m "*MVS_SYSPLEX"
tacmd histstartcollection -a "System CPU Utilization" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "System Paging Activity" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "Tape Drives" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "TopUser" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "User Response Time" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "USS Address Spaces" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "USS BPXPRMxx Values" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "USS Kernel" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "USS Logged on Users" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "USS Mounted File Systems" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "USS Processes" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "USS Threads" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "WLM Class Sysplex Metrics" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "WLM Service Class Resources" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "WLM Service Class Resources History" -m "*MVS_SYSTEM"
tacmd histstartcollection -a "XCF Group" -m "*MVS_SYSPLEX"
tacmd histstartcollection -a "XCF Members" -m "*MVS_SYSPLEX"
tacmd histstartcollection -a "XCF Paths" -m "*MVS_SYSPLEX"
tacmd histstartcollection -a "XCF System" -m "*MVS_SYSPLEX"
tacmd histstartcollection -a "XCF System Statistics" -m "*MVS_SYSPLEX"
