tacmd histdeletecollection -a "Address Space ComStor Owned" 
tacmd histdeletecollection -a "Address Space CPU Summary History" 
tacmd histdeletecollection -a "Address Space CPU Utilization" 
tacmd histdeletecollection -a "Address Space CPU Utilization History" 
tacmd histdeletecollection -a "Address Space Delay Summary History" 
tacmd histdeletecollection -a "Address Space Real Storage" 
tacmd histdeletecollection -a "Address Space Summary" 
tacmd histdeletecollection -a "Address Space Virtual Storage" 
tacmd histdeletecollection -a "CF Channel Paths" 
tacmd histdeletecollection -a "CF Clients" 
tacmd histdeletecollection -a "CF Path" 
tacmd histdeletecollection -a "CF Policy" 
tacmd histdeletecollection -a "CF Structure to MVS System" 
tacmd histdeletecollection -a "CF Structures" 
tacmd histdeletecollection -a "CF Systems" 
tacmd histdeletecollection -a "Channel Paths" 
tacmd histdeletecollection -a "Common Storage" 
tacmd histdeletecollection -a "Common Storage Utilization History" 
tacmd histdeletecollection -a "CPC LPAR Details History" 
tacmd histdeletecollection -a "CPC LPAR Summary History" 
tacmd histdeletecollection -a "DASD MVS" 
tacmd histdeletecollection -a "DASD MVS Devices" 
tacmd histdeletecollection -a "Enclave Table" 
tacmd histdeletecollection -a "Enqueues" 
tacmd histdeletecollection -a "Global Enqueues" 
tacmd histdeletecollection -a "HiperDispatch Logical Processors" 
tacmd histdeletecollection -a "HiperDispatch Management" 
tacmd histdeletecollection -a "JES Spool Details" 
tacmd histdeletecollection -a "KM5 Address Space Storage SubKey" 
tacmd histdeletecollection -a "KM5 Common Storage SubKey" 
tacmd histdeletecollection -a "KM5 Device Job History" 
tacmd histdeletecollection -a "KM5 Device Resource History" 
tacmd histdeletecollection -a "KM5 Health Checks" 
tacmd histdeletecollection -a "KM5 License Manager MSU WLM Cap" 
tacmd histdeletecollection -a "KM5 MultiThreading Details" 
tacmd histdeletecollection -a "KM5 MultiThreading Summary" 
tacmd histdeletecollection -a "KM5 Spin Lock" 
tacmd histdeletecollection -a "KM5 Storage Details History" 
tacmd histdeletecollection -a "KM5 Storage Shortage Status" 
tacmd histdeletecollection -a "KM5 Storage Summary History" 
tacmd histdeletecollection -a "KM5 StorageClassMemory Details" 
tacmd histdeletecollection -a "KM5 StorageClassMemory Summary" 
tacmd histdeletecollection -a "KM5 Suspend Lock" 
tacmd histdeletecollection -a "KM5 zFS Directory Cache" 
tacmd histdeletecollection -a "KM5 zFS Kernel" 
tacmd histdeletecollection -a "KM5 zFS Metadata Cache" 
tacmd histdeletecollection -a "KM5 zFS Storage" 
tacmd histdeletecollection -a "KM5 zFS User Cache" 
tacmd histdeletecollection -a "KM5 zFS User Cache DS" 
tacmd histdeletecollection -a "LPAR Clusters" 
tacmd histdeletecollection -a "LPAR Summary History" 
tacmd histdeletecollection -a "Operator Alerts" 
tacmd histdeletecollection -a "Page Dataset Activity" 
tacmd histdeletecollection -a "PCIE Device Summary" 
tacmd histdeletecollection -a "Real Storage" 
tacmd histdeletecollection -a "Real Storage Utilization History" 
tacmd histdeletecollection -a "Report Classes" 
tacmd histdeletecollection -a "Resource Groups" 
tacmd histdeletecollection -a "SCM Device Summary" 
tacmd histdeletecollection -a "Service Class Address Spaces" 
tacmd histdeletecollection -a "Service Class Enqueue Workflow Analysis" 
tacmd histdeletecollection -a "Service Class I/O Workflow Analysis" 
tacmd histdeletecollection -a "Service Class Subsys Workflow Analysis" 
tacmd histdeletecollection -a "Service Definition" 
tacmd histdeletecollection -a "SVCDET" 
tacmd histdeletecollection -a "Sysplex DASD" 
tacmd histdeletecollection -a "Sysplex DASD Device" 
tacmd histdeletecollection -a "Sysplex DASD Group" 
tacmd histdeletecollection -a "Sysplex WLM Service Class Period" 
tacmd histdeletecollection -a "Sysplexes Coupling Facility" 
tacmd histdeletecollection -a "System CPU Utilization" 
tacmd histdeletecollection -a "System Paging Activity" 
tacmd histdeletecollection -a "Tape Drives" 
tacmd histdeletecollection -a "TopUser" 
tacmd histdeletecollection -a "User Response Time" 
tacmd histdeletecollection -a "USS Address Spaces" 
tacmd histdeletecollection -a "USS BPXPRMxx Values" 
tacmd histdeletecollection -a "USS Kernel" 
tacmd histdeletecollection -a "USS Logged on Users" 
tacmd histdeletecollection -a "USS Mounted File Systems" 
tacmd histdeletecollection -a "USS Processes" 
tacmd histdeletecollection -a "USS Threads" 
tacmd histdeletecollection -a "WLM Class Sysplex Metrics" 
tacmd histdeletecollection -a "WLM Service Class Resources" 
tacmd histdeletecollection -a "WLM Service Class Resources History" 
tacmd histdeletecollection -a "XCF Group" 
tacmd histdeletecollection -a "XCF Members" 
tacmd histdeletecollection -a "XCF Paths" 
tacmd histdeletecollection -a "XCF System" 
tacmd histdeletecollection -a "XCF System Statistics" 
