
tacmd histstopcollection -a "Application Accounting" -m "*MVS_MQM"
tacmd histstopcollection -a "Application Connections" -m "*MVS_MQM"
tacmd histstopcollection -a "Application Long-Term History" -m "*MVS_MQM"
tacmd histstopcollection -a "Application Queue Long-Term History" -m "*MVS_MQM"
tacmd histstopcollection -a "Application Transaction/Program Long-Term History" -m "*MVS_MQM"
tacmd histstopcollection -a "Buffer Manager Long-Term History" -m "*MVS_MQM"
tacmd histstopcollection -a "Channel Data" -m "*MVS_MQM"
tacmd histstopcollection -a "Channel Definitions" -m "*MVS_MQM"
tacmd histstopcollection -a "Channel Initiator Detail" -m "*MVS_MQM"
tacmd histstopcollection -a "Channel Long-Term History" -m "*MVS_MQM"
tacmd histstopcollection -a "Channel Status" -m "*MVS_MQM"
tacmd histstopcollection -a "Channel Summary" -m "*MVS_MQM"
tacmd histstopcollection -a "Connection Objects" -m "*MVS_MQM"
tacmd histstopcollection -a "Current Queue Manager Status" -m "*MVS_MQM"
tacmd histstopcollection -a "Error Log" -m "*MVS_MQM"
tacmd histstopcollection -a "Event Archive" -m "*MVS_MQM"
tacmd histstopcollection -a "Listener Status" -m "*MVS_MQM"
tacmd histstopcollection -a "Log Data Set Status" -m "*MVS_MQM"
tacmd histstopcollection -a "Log Manager Long-Term History" -m "*MVS_MQM"
tacmd histstopcollection -a "Message Manager Long-Term History" -m "*MVS_MQM"
tacmd histstopcollection -a "Message Statistics" -m "*MVS_MQM"
tacmd histstopcollection -a "MQ Action Log" -m "*MVS_MQM"
tacmd histstopcollection -a "MQ Channel Statistics" -m "*MVS_MQM"
tacmd histstopcollection -a "MQ Queue Statistics" -m "*MVS_MQM"
tacmd histstopcollection -a "MQI Call Statistics Details" -m "*MVS_MQM"
tacmd histstopcollection -a "MQI Message Statistics Details" -m "*MVS_MQM"
tacmd histstopcollection -a "MQI Statistics" -m "*MVS_MQM"
tacmd histstopcollection -a "Page Set Long-Term History" -m "*MVS_MQM"
tacmd histstopcollection -a "Process Information" -m "*MVS_MQM"
tacmd histstopcollection -a "QSG Channels" -m "*MVS_MQM"
tacmd histstopcollection -a "QSG Coupling Facility Structure Backups" -m "*MVS_MQM"
tacmd histstopcollection -a "QSG Coupling Facility Structure Connections" -m "*MVS_MQM"
tacmd histstopcollection -a "QSG Coupling Facility Structures" -m "*MVS_MQM"
tacmd histstopcollection -a "QSG QMgrs" -m "*MVS_MQM"
tacmd histstopcollection -a "QSG Queues" -m "*MVS_MQM"
tacmd histstopcollection -a "Queue Accounting" -m "*MVS_MQM"
tacmd histstopcollection -a "Queue Data" -m "*MVS_MQM"
tacmd histstopcollection -a "Queue Definitions" -m "*MVS_MQM"
tacmd histstopcollection -a "Queue Handle Status" -m "*MVS_MQM"
tacmd histstopcollection -a "Queue Long Term History" -m "*MVS_MQM"
tacmd histstopcollection -a "Queue Status" -m "*MVS_MQM"
tacmd histstopcollection -a "SMDS Long-Term History" -m "*MVS_MQM"
tacmd histstopcollection -a "Telemetry Channels" -m "*MVS_MQM"
tacmd histstopcollection -a "Topic Manager Long-Term History" -m "*MVS_MQM"
