tacmd histdeletecollection -a "Application Accounting"
tacmd histdeletecollection -a "Application Connections"
tacmd histdeletecollection -a "Application Long-Term History"
tacmd histdeletecollection -a "Application Queue Long-Term History"
tacmd histdeletecollection -a "Application Transaction/Program Long-Term History"
tacmd histdeletecollection -a "Buffer Manager Long-Term History"
tacmd histdeletecollection -a "Channel Data"
tacmd histdeletecollection -a "Channel Definitions"
tacmd histdeletecollection -a "Channel Initiator Detail"
tacmd histdeletecollection -a "Channel Long-Term History"
tacmd histdeletecollection -a "Channel Status"
tacmd histdeletecollection -a "Channel Summary"
tacmd histdeletecollection -a "Connection Objects"
tacmd histdeletecollection -a "Current Queue Manager Status"
tacmd histdeletecollection -a "Error Log"
tacmd histdeletecollection -a "Event Archive"
tacmd histdeletecollection -a "Listener Status"
tacmd histdeletecollection -a "Log Data Set Status"
tacmd histdeletecollection -a "Log Manager Long-Term History"
tacmd histdeletecollection -a "Message Manager Long-Term History"
tacmd histdeletecollection -a "Message Statistics"
tacmd histdeletecollection -a "MQ Action Log"
tacmd histdeletecollection -a "MQ Channel Statistics"
tacmd histdeletecollection -a "MQ Queue Statistics"
tacmd histdeletecollection -a "MQI Call Statistics Details"
tacmd histdeletecollection -a "MQI Message Statistics Details"
tacmd histdeletecollection -a "MQI Statistics"
tacmd histdeletecollection -a "Page Set Long-Term History"
tacmd histdeletecollection -a "Process Information"
tacmd histdeletecollection -a "QSG Channels"
tacmd histdeletecollection -a "QSG Coupling Facility Structure Backups"
tacmd histdeletecollection -a "QSG Coupling Facility Structure Connections"
tacmd histdeletecollection -a "QSG Coupling Facility Structures"
tacmd histdeletecollection -a "QSG QMgrs"
tacmd histdeletecollection -a "QSG Queues"
tacmd histdeletecollection -a "Queue Accounting"
tacmd histdeletecollection -a "Queue Data"
tacmd histdeletecollection -a "Queue Definitions"
tacmd histdeletecollection -a "Queue Handle Status"
tacmd histdeletecollection -a "Queue Long Term History"
tacmd histdeletecollection -a "Queue Status"
tacmd histdeletecollection -a "SMDS Long-Term History"
tacmd histdeletecollection -a "Telemetry Channels"
tacmd histdeletecollection -a "Topic Manager Long-Term History"
