tacmd histstopcollection -a "CSM Storage" -m "*OMEGAMONXE_MAINFRAME_NTWK_VTAM"
tacmd histstopcollection -a "Current IP Filters" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "Dynamic IP Tunnels" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "EE Connections" -m "*OMEGAMONXE_MAINFRAME_NTWK_VTAM"
tacmd histstopcollection -a "EE Connections Details" -m "*OMEGAMONXE_MAINFRAME_NTWK_VTAM"
tacmd histstopcollection -a "FTP Sessions" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "HPR RTP Connections" -m "*OMEGAMONXE_MAINFRAME_NTWK_VTAM"
tacmd histstopcollection -a "IKE Tunnels" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "Interfaces" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "IPSec Status" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "KN3 Agent Status" -m "*OMEGAMONXE_MAINFRAME_NTWK"
tacmd histstopcollection -a "KN3 CSM Storage by Owner" -m "*OMEGAMONXE_MAINFRAME_NTWK_VTAM"
tacmd histstopcollection -a "KN3 ICMP Global Counters" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "KN3 ICMP Type Counters" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "KN3 Interface Address" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "KN3 Interface Read Queue" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "KN3 Interface Statistics" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "KN3 Interface Status" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "KN3 Interface Write Queue" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "KN3 IP Counter Statistics" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "KN3 IP General Statistics" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "KN3 OSA Express5S Ports Control" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "KN3 OSA Express5S Ports Errors" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "KN3 OSA Express5S Ports Summary" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "KN3 OSA Express5S Ports THR" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "KN3 OSA Express7 Ports Control" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "KN3 OSA Express7 Ports Errors" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "KN3 OSA Express7 Ports Summary" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "KN3 OSA Express7 Ports THR" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "KN3 SNA Collector Status" -m "*OMEGAMONXE_MAINFRAME_NTWK"
tacmd histstopcollection -a "KN3 Take Action Command" -m "*OMEGAMONXE_MAINFRAME_NTWK"
tacmd histstopcollection -a "KN3 Take Action Command Response" -m "*OMEGAMONXE_MAINFRAME_NTWK"
tacmd histstopcollection -a "KN3 TCP Collector Status" -m "*OMEGAMONXE_MAINFRAME_NTWK"
tacmd histstopcollection -a "KN3 TCP Counter Statistics" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "KN3 TCPIP Cmd Ctrl" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "KN3 UDP Counter Statistics" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "Manual IP Tunnels" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "OSA 10Gigabit Ports Control" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "OSA 10Gigabit Ports Errors" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "OSA 10Gigabit Ports Summary" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "OSA 10Gigabit Ports Throughput" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "OSA Express3 Ports Control" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "OSA Express3 Ports Errors" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "OSA Express3 Ports Summary" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "OSA Express3 Ports Throughput" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "OSA Express Channels" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "OSA Express LPARS" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "OSA Express Ports" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "TCP Listener" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "TCPIP Address Space" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "TCPIP Applications" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "TCPIP Connections" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "TCPIP Details" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "TCPIP Devices" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "TCPIP FTP" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "TCPIP Gateways" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "TCPIP Memory Statistics" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "TCPIP Stack Layer" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "TN3270 Response Time Buckets" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "TN3270 Server Sess Avail" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "UDP Connections" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "VTAM Address Space" -m "*OMEGAMONXE_MAINFRAME_NTWK_VTAM"
tacmd histstopcollection -a "VTAM Application Data" -m "*OMEGAMONXE_MAINFRAME_NTWK_VTAM"
tacmd histstopcollection -a "VTAM Applid Data" -m "*OMEGAMONXE_MAINFRAME_NTWK_VTAM"
tacmd histstopcollection -a "VTAM Buffer Pool Extents" -m "*OMEGAMONXE_MAINFRAME_NTWK_VTAM"
tacmd histstopcollection -a "VTAM Buffer Pools" -m "*OMEGAMONXE_MAINFRAME_NTWK_VTAM"
tacmd histstopcollection -a "VTAM Buffer Usage by Address Space" -m "*OMEGAMONXE_MAINFRAME_NTWK_VTAM"
tacmd histstopcollection -a "VTAM Buffer Usage by Application" -m "*OMEGAMONXE_MAINFRAME_NTWK_VTAM"
tacmd histstopcollection -a "VTAM Buffer Usage by Category" -m "*OMEGAMONXE_MAINFRAME_NTWK_VTAM"
tacmd histstopcollection -a "VTAM Session Data" -m "*OMEGAMONXE_MAINFRAME_NTWK_VTAM"
tacmd histstopcollection -a "VTAM SIO" -m "*OMEGAMONXE_MAINFRAME_NTWK_VTAM"
tacmd histstopcollection -a "VTAM Summary Statistics" -m "*OMEGAMONXE_MAINFRAME_NTWK_VTAM"
tacmd histstopcollection -a "zERT Common Session Data" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "zERT DNS Session Data" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "zERT IPSec Session Data" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "zERT SSH Session Data" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
tacmd histstopcollection -a "zERT TLS Session Data" -m "*OMEGAMONXE_MAINFRAME_NTWK_TCP"
