tacmd histdeletecollection -a "CSM Storage" 
tacmd histdeletecollection -a "Current IP Filters" 
tacmd histdeletecollection -a "Dynamic IP Tunnels" 
tacmd histdeletecollection -a "EE Connections" 
tacmd histdeletecollection -a "EE Connections Details" 
tacmd histdeletecollection -a "FTP Sessions" 
tacmd histdeletecollection -a "HPR RTP Connections" 
tacmd histdeletecollection -a "IKE Tunnels" 
tacmd histdeletecollection -a "Interfaces" 
tacmd histdeletecollection -a "IPSec Status" 
tacmd histdeletecollection -a "KN3 Agent Status" 
tacmd histdeletecollection -a "KN3 CSM Storage by Owner" 
tacmd histdeletecollection -a "KN3 ICMP Global Counters" 
tacmd histdeletecollection -a "KN3 ICMP Type Counters" 
tacmd histdeletecollection -a "KN3 Interface Address" 
tacmd histdeletecollection -a "KN3 Interface Read Queue" 
tacmd histdeletecollection -a "KN3 Interface Statistics" 
tacmd histdeletecollection -a "KN3 Interface Status" 
tacmd histdeletecollection -a "KN3 Interface Write Queue" 
tacmd histdeletecollection -a "KN3 IP Counter Statistics" 
tacmd histdeletecollection -a "KN3 IP General Statistics" 
tacmd histdeletecollection -a "KN3 OSA Express5S Ports Control" 
tacmd histdeletecollection -a "KN3 OSA Express5S Ports Errors" 
tacmd histdeletecollection -a "KN3 OSA Express5S Ports Summary" 
tacmd histdeletecollection -a "KN3 OSA Express5S Ports THR" 
tacmd histdeletecollection -a "KN3 OSA Express7 Ports Control" 
tacmd histdeletecollection -a "KN3 OSA Express7 Ports Errors" 
tacmd histdeletecollection -a "KN3 OSA Express7 Ports Summary" 
tacmd histdeletecollection -a "KN3 OSA Express7 Ports THR" 
tacmd histdeletecollection -a "KN3 SNA Collector Status" 
tacmd histdeletecollection -a "KN3 Take Action Command" 
tacmd histdeletecollection -a "KN3 Take Action Command Response" 
tacmd histdeletecollection -a "KN3 TCP Collector Status" 
tacmd histdeletecollection -a "KN3 TCP Counter Statistics" 
tacmd histdeletecollection -a "KN3 TCPIP Cmd Ctrl" 
tacmd histdeletecollection -a "KN3 UDP Counter Statistics" 
tacmd histdeletecollection -a "Manual IP Tunnels" 
tacmd histdeletecollection -a "OSA 10Gigabit Ports Control" 
tacmd histdeletecollection -a "OSA 10Gigabit Ports Errors" 
tacmd histdeletecollection -a "OSA 10Gigabit Ports Summary" 
tacmd histdeletecollection -a "OSA 10Gigabit Ports Throughput" 
tacmd histdeletecollection -a "OSA Express3 Ports Control" 
tacmd histdeletecollection -a "OSA Express3 Ports Errors" 
tacmd histdeletecollection -a "OSA Express3 Ports Summary" 
tacmd histdeletecollection -a "OSA Express3 Ports Throughput" 
tacmd histdeletecollection -a "OSA Express Channels" 
tacmd histdeletecollection -a "OSA Express LPARS" 
tacmd histdeletecollection -a "OSA Express Ports" 
tacmd histdeletecollection -a "TCP Listener" 
tacmd histdeletecollection -a "TCPIP Address Space" 
tacmd histdeletecollection -a "TCPIP Applications" 
tacmd histdeletecollection -a "TCPIP Connections" 
tacmd histdeletecollection -a "TCPIP Details" 
tacmd histdeletecollection -a "TCPIP Devices" 
tacmd histdeletecollection -a "TCPIP FTP" 
tacmd histdeletecollection -a "TCPIP Gateways" 
tacmd histdeletecollection -a "TCPIP Memory Statistics" 
tacmd histdeletecollection -a "TCPIP Stack Layer" 
tacmd histdeletecollection -a "TN3270 Response Time Buckets" 
tacmd histdeletecollection -a "TN3270 Server Sess Avail" 
tacmd histdeletecollection -a "UDP Connections" 
tacmd histdeletecollection -a "VTAM Address Space" 
tacmd histdeletecollection -a "VTAM Application Data" 
tacmd histdeletecollection -a "VTAM Applid Data" 
tacmd histdeletecollection -a "VTAM Buffer Pool Extents" 
tacmd histdeletecollection -a "VTAM Buffer Pools" 
tacmd histdeletecollection -a "VTAM Buffer Usage by Address Space" 
tacmd histdeletecollection -a "VTAM Buffer Usage by Application" 
tacmd histdeletecollection -a "VTAM Buffer Usage by Category" 
tacmd histdeletecollection -a "VTAM Session Data" 
tacmd histdeletecollection -a "VTAM SIO" 
tacmd histdeletecollection -a "VTAM Summary Statistics" 
tacmd histdeletecollection -a "zERT Common Session Data" 
tacmd histdeletecollection -a "zERT DNS Session Data" 
tacmd histdeletecollection -a "zERT IPSec Session Data" 
tacmd histdeletecollection -a "zERT SSH Session Data" 
tacmd histdeletecollection -a "zERT TLS Session Data" 
