tacmd histstartcollection -a "Accounting Message Flow Statistics" -m "*MQSI_BROKER_V7"
tacmd histstartcollection -a "Accounting Node Statistics" -m "*MQSI_BROKER_V7"
tacmd histstartcollection -a "Accounting Terminal Statistics" -m "*MQSI_BROKER_V7"
tacmd histstartcollection -a "Accounting Thread Statistics" -m "*MQSI_BROKER_V7"
tacmd histstartcollection -a "Broker Status" -m "*MQSI_BROKER_V7"
tacmd histstartcollection -a "Broker Status Events" -m "*MQSI_BROKER_V7"
tacmd histstartcollection -a "CICS Resource Statistics" -m "*MQSI_BROKER_V7"
tacmd histstartcollection -a "Components" -m "*MQSI_AGENT"
tacmd histstartcollection -a "Execution Group Status" -m "*MQSI_BROKER_V7"
tacmd histstartcollection -a "File Resource Statistics" -m "*MQSI_BROKER_V7"
tacmd histstartcollection -a "Global Cache Resource Statistics" -m "*MQSI_BROKER_V7"
tacmd histstartcollection -a "JDBC Connection Pools Resource Statistics" -m "*MQSI_BROKER_V7"
tacmd histstartcollection -a "JMS Resource Statistics" -m "*MQSI_BROKER_V7"
tacmd histstartcollection -a "JVM Resource Statistics" -m "*MQSI_BROKER_V7"
tacmd histstartcollection -a "Message Flow Status" -m "*MQSI_BROKER_V7"
tacmd histstartcollection -a "Monitor Node Base Statistics" -m "*MQSI_BROKER_V7"
tacmd histstartcollection -a "Monitor Node Broker Statistics" -m "*MQSI_BROKER_V7"
tacmd histstartcollection -a "Monitor Node Events" -m "*MQSI_BROKER_V7"
tacmd histstartcollection -a "Monitor Node Execution Group Statistics" -m "*MQSI_BROKER_V7"
tacmd histstartcollection -a "Monitor Node Message Flow Statistics" -m "*MQSI_BROKER_V7"
tacmd histstartcollection -a "Monitor Node Sub-Flow Statistics" -m "*MQSI_BROKER_V7"
tacmd histstartcollection -a "ODBC Resource Statistics" -m "*MQSI_BROKER_V7"
tacmd histstartcollection -a "Parsers Resource Statistics" -m "*MQSI_BROKER_V7"
tacmd histstartcollection -a "Product Events" -m "*MQSI_AGENT"
tacmd histstartcollection -a "SOAPInput Resource Statistics" -m "*MQSI_BROKER_V7"
tacmd histstartcollection -a "Sockets Resource Statistics" -m "*MQSI_BROKER_V7"
tacmd histstartcollection -a "TCPIP Client Nodes Resource Statistics" -m "*MQSI_BROKER_V7"
tacmd histstartcollection -a "TCPIP Server Nodes Resource Statistics" -m "*MQSI_BROKER_V7"
