tacmd histdeletecollection -a "Accounting Message Flow Statistics"
tacmd histdeletecollection -a "Accounting Node Statistics"
tacmd histdeletecollection -a "Accounting Terminal Statistics"
tacmd histdeletecollection -a "Accounting Thread Statistics"
tacmd histdeletecollection -a "Broker Status"
tacmd histdeletecollection -a "Broker Status Events"
tacmd histdeletecollection -a "CICS Resource Statistics"
tacmd histdeletecollection -a "Components"
tacmd histdeletecollection -a "Execution Group Status"
tacmd histdeletecollection -a "File Resource Statistics"
tacmd histdeletecollection -a "Global Cache Resource Statistics"
tacmd histdeletecollection -a "JDBC Connection Pools Resource Statistics"
tacmd histdeletecollection -a "JMS Resource Statistics"
tacmd histdeletecollection -a "JVM Resource Statistics"
tacmd histdeletecollection -a "Message Flow Status"
tacmd histdeletecollection -a "Monitor Node Base Statistics"
tacmd histdeletecollection -a "Monitor Node Broker Statistics"
tacmd histdeletecollection -a "Monitor Node Events"
tacmd histdeletecollection -a "Monitor Node Execution Group Statistics"
tacmd histdeletecollection -a "Monitor Node Message Flow Statistics"
tacmd histdeletecollection -a "Monitor Node Sub-Flow Statistics"
tacmd histdeletecollection -a "ODBC Resource Statistics"
tacmd histdeletecollection -a "Parsers Resource Statistics"
tacmd histdeletecollection -a "Product Events"
tacmd histdeletecollection -a "SOAPInput Resource Statistics"
tacmd histdeletecollection -a "Sockets Resource Statistics"
tacmd histdeletecollection -a "TCPIP Client Nodes Resource Statistics"
tacmd histdeletecollection -a "TCPIP Server Nodes Resource Statistics"
