

tacmd histstartcollection -a "S3 ADABAS Data Bases" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 ADABAS DB Files" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 ADABAS Volumes" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Application Dataset Details" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Application Monitoring" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 CA1 Configuration" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 CA1 Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Cache Control Unit" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Cache Devices" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Channel Path" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 DASD Group Vol Perform" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 DASD Group Vol Space" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 DASD Volume Performance" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 DASD Volume Space" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Dataset Attributes Blocksize Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Dataset Attributes CA Split Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Dataset Attributes Catalog Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Dataset Attributes CI Split Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Dataset Attributes Creation Date Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Dataset Attributes DSORG Detail" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Dataset Attributes DSORG Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Dataset Attributes Extent Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Dataset Attributes HLQSummary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Dataset Attributes Inefficient Blocksize Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Dataset Attributes Mature Dataset Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Dataset Attributes Never Referenced Dataset Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Dataset Attributes Newborn Dataset Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Dataset Attributes Reference Date Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Dataset Attributes SMS Class Detail" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Dataset Attributes SMS Class Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Dataset Attributes Space Allocated Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Dataset Attributes Space Unused Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Dataset Attributes System Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Dataset Attributes Uncataloged Detail" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Dataset Attributes Uncataloged Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Dataset Group Detail Attrs" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Dataset Group Details" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Dataset Group Details Volume" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Dataset Group Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 DSN Attr Group Detail" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 DSN Attr Group Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 FICON Director Control Units" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 FICON Director Ports" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 FICON Director Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Flash Copy Relation" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Flash Copy Volume" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 HSM CDS" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 HSM Common Storage" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 HSM Cross System CRQ Hosts" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 HSM Cross System CRQplex" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 HSM Function Details" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 HSM Function Statistics" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 HSM Function Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 HSM Host Function Status" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 HSM Host Request Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 HSM Host Status" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 HSM Private Storage" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 HSM Requests" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 HSM Status" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Link Statistics" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Logical Control Unit" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 PPRC Connection" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 PPRC Volume" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 RLS Appl Dataset Details" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 RLS Buffer LSU Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 RLS Buffer Pool Detail" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 RLS Dataset Group Details" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 RLS Dataset Group Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 RLS Lock Structure" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 RLS Lock Structure CF Detail" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 RLS Performance Overview" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 RLS Storage Class" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 RMM Config" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 RMM Control Dataset" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 RMM Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 SMS Cache Sets" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 SMS Configuration" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 SMS Data Class" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 SMS Management Class" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 SMS Storage Class" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 SMS Storage Group" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 SMS Storage Group Status" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 SMS Systems" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Tape Device" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Tape Group" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 UDG Cache Devices" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 Volume Group Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 VTS Cache Partition Container Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 VTS Cache Preference Group Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 VTS Cluster Replication" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 VTS Cluster Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 VTS Overview" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 VTS Tape Volume Cache Summary" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 VTSS Channels" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 VTSS Configuration" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 VTSS Queued Tasks" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 VTSS Real Tape Drives" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 VTSS Status" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 VTSS Virtual Volumes" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 XRC Session" -m "*OMEGAMONXE_SMS"
tacmd histstartcollection -a "S3 XRC Volume Pair" -m "*OMEGAMONXE_SMS"

