

tacmd histdeletecollection -a "S3 ADABAS Data Bases" 
tacmd histdeletecollection -a "S3 ADABAS DB Files" 
tacmd histdeletecollection -a "S3 ADABAS Volumes" 
tacmd histdeletecollection -a "S3 Application Dataset Details" 
tacmd histdeletecollection -a "S3 Application Monitoring" 
tacmd histdeletecollection -a "S3 CA1 Configuration" 
tacmd histdeletecollection -a "S3 CA1 Summary" 
tacmd histdeletecollection -a "S3 Cache Control Unit" 
tacmd histdeletecollection -a "S3 Cache Devices" 
tacmd histdeletecollection -a "S3 Channel Path" 
tacmd histdeletecollection -a "S3 DASD Group Vol Perform" 
tacmd histdeletecollection -a "S3 DASD Group Vol Space" 
tacmd histdeletecollection -a "S3 DASD Volume Performance" 
tacmd histdeletecollection -a "S3 DASD Volume Space" 
tacmd histdeletecollection -a "S3 Dataset Attributes Blocksize Summary" 
tacmd histdeletecollection -a "S3 Dataset Attributes CA Split Summary" 
tacmd histdeletecollection -a "S3 Dataset Attributes Catalog Summary" 
tacmd histdeletecollection -a "S3 Dataset Attributes CI Split Summary" 
tacmd histdeletecollection -a "S3 Dataset Attributes Creation Date Summary" 
tacmd histdeletecollection -a "S3 Dataset Attributes DSORG Detail" 
tacmd histdeletecollection -a "S3 Dataset Attributes DSORG Summary" 
tacmd histdeletecollection -a "S3 Dataset Attributes Extent Summary" 
tacmd histdeletecollection -a "S3 Dataset Attributes HLQSummary" 
tacmd histdeletecollection -a "S3 Dataset Attributes Inefficient Blocksize Summary" 
tacmd histdeletecollection -a "S3 Dataset Attributes Mature Dataset Summary" 
tacmd histdeletecollection -a "S3 Dataset Attributes Never Referenced Dataset Summary" 
tacmd histdeletecollection -a "S3 Dataset Attributes Newborn Dataset Summary" 
tacmd histdeletecollection -a "S3 Dataset Attributes Reference Date Summary" 
tacmd histdeletecollection -a "S3 Dataset Attributes SMS Class Detail" 
tacmd histdeletecollection -a "S3 Dataset Attributes SMS Class Summary" 
tacmd histdeletecollection -a "S3 Dataset Attributes Space Allocated Summary" 
tacmd histdeletecollection -a "S3 Dataset Attributes Space Unused Summary" 
tacmd histdeletecollection -a "S3 Dataset Attributes System Summary" 
tacmd histdeletecollection -a "S3 Dataset Attributes Uncataloged Detail" 
tacmd histdeletecollection -a "S3 Dataset Attributes Uncataloged Summary" 
tacmd histdeletecollection -a "S3 Dataset Group Detail Attrs" 
tacmd histdeletecollection -a "S3 Dataset Group Details" 
tacmd histdeletecollection -a "S3 Dataset Group Details Volume" 
tacmd histdeletecollection -a "S3 Dataset Group Summary" 
tacmd histdeletecollection -a "S3 DSN Attr Group Detail" 
tacmd histdeletecollection -a "S3 DSN Attr Group Summary" 
tacmd histdeletecollection -a "S3 FICON Director Control Units" 
tacmd histdeletecollection -a "S3 FICON Director Ports" 
tacmd histdeletecollection -a "S3 FICON Director Summary" 
tacmd histdeletecollection -a "S3 Flash Copy Relation" 
tacmd histdeletecollection -a "S3 Flash Copy Volume" 
tacmd histdeletecollection -a "S3 HSM CDS" 
tacmd histdeletecollection -a "S3 HSM Common Storage" 
tacmd histdeletecollection -a "S3 HSM Cross System CRQ Hosts" 
tacmd histdeletecollection -a "S3 HSM Cross System CRQplex" 
tacmd histdeletecollection -a "S3 HSM Function Details" 
tacmd histdeletecollection -a "S3 HSM Function Statistics" 
tacmd histdeletecollection -a "S3 HSM Function Summary" 
tacmd histdeletecollection -a "S3 HSM Host Function Status" 
tacmd histdeletecollection -a "S3 HSM Host Request Summary" 
tacmd histdeletecollection -a "S3 HSM Host Status" 
tacmd histdeletecollection -a "S3 HSM Private Storage" 
tacmd histdeletecollection -a "S3 HSM Requests" 
tacmd histdeletecollection -a "S3 HSM Status" 
tacmd histdeletecollection -a "S3 Link Statistics" 
tacmd histdeletecollection -a "S3 Logical Control Unit" 
tacmd histdeletecollection -a "S3 PPRC Connection" 
tacmd histdeletecollection -a "S3 PPRC Volume" 
tacmd histdeletecollection -a "S3 RLS Appl Dataset Details" 
tacmd histdeletecollection -a "S3 RLS Buffer LSU Summary" 
tacmd histdeletecollection -a "S3 RLS Buffer Pool Detail" 
tacmd histdeletecollection -a "S3 RLS Dataset Group Details" 
tacmd histdeletecollection -a "S3 RLS Dataset Group Summary" 
tacmd histdeletecollection -a "S3 RLS Lock Structure" 
tacmd histdeletecollection -a "S3 RLS Lock Structure CF Detail" 
tacmd histdeletecollection -a "S3 RLS Performance Overview" 
tacmd histdeletecollection -a "S3 RLS Storage Class" 
tacmd histdeletecollection -a "S3 RMM Config" 
tacmd histdeletecollection -a "S3 RMM Control Dataset" 
tacmd histdeletecollection -a "S3 RMM Summary" 
tacmd histdeletecollection -a "S3 SMS Cache Sets" 
tacmd histdeletecollection -a "S3 SMS Configuration" 
tacmd histdeletecollection -a "S3 SMS Data Class" 
tacmd histdeletecollection -a "S3 SMS Management Class" 
tacmd histdeletecollection -a "S3 SMS Storage Class" 
tacmd histdeletecollection -a "S3 SMS Storage Group" 
tacmd histdeletecollection -a "S3 SMS Storage Group Status" 
tacmd histdeletecollection -a "S3 SMS Systems" 
tacmd histdeletecollection -a "S3 Tape Device" 
tacmd histdeletecollection -a "S3 Tape Group" 
tacmd histdeletecollection -a "S3 UDG Cache Devices" 
tacmd histdeletecollection -a "S3 Volume Group Summary" 
tacmd histdeletecollection -a "S3 VTS Cache Partition Container Summary" 
tacmd histdeletecollection -a "S3 VTS Cache Preference Group Summary" 
tacmd histdeletecollection -a "S3 VTS Cluster Replication" 
tacmd histdeletecollection -a "S3 VTS Cluster Summary" 
tacmd histdeletecollection -a "S3 VTS Overview" 
tacmd histdeletecollection -a "S3 VTS Tape Volume Cache Summary" 
tacmd histdeletecollection -a "S3 VTSS Channels" 
tacmd histdeletecollection -a "S3 VTSS Configuration" 
tacmd histdeletecollection -a "S3 VTSS Queued Tasks" 
tacmd histdeletecollection -a "S3 VTSS Real Tape Drives" 
tacmd histdeletecollection -a "S3 VTSS Status" 
tacmd histdeletecollection -a "S3 VTSS Virtual Volumes" 
tacmd histdeletecollection -a "S3 XRC Session" 
tacmd histdeletecollection -a "S3 XRC Volume Pair" 


