classes = ['classes/ae.jar', 'classes/browser-core-winnt64.jar', 'classes/browser-winnt64.jar',
           'classes/browser.jar', 'classes/chart.jar', 'classes/cnp.jar', 'classes/cnp_jviewsall.jar',
           'classes/cnp_ps.jar', 'classes/cnp_vbjorball.jar', 'classes/deploy.jar',
           'classes/kdy_resources.jar',
           'classes/khd_resources.jar',
           'classes/khd.jar',
           'classes/kib_resources.jar',
           'classes/kib_resources.jar',
           'classes/ksy_resources.jar',
           'classes/ksy.jar',
           'classes/kcp_resources.jar',
           'classes/kit.jar',
           'classes/knt_resources.jar',
           'classes/kpa_resources.jar',
           'classes/kul_resources.jar',
           'classes/kum_resources.jar',
           'classes/kux_resources.jar',
           'classes/kdp_resources.jar',
           'classes/kgw_resources.jar',
           'classes/kip_resources.jar',
           'classes/kjj_resources.jar',
           'classes/kmq_resources.jar',
           'classes/km5_resources.jar',
           'classes/kn3_resources.jar',
           'classes/kqi_resources.jar',
           'classes/ks3_resources.jar',
           'classes/ks3.jar',
           'classes/kjrall.jar', 'classes/terminal.jar', 'classes/util.jar',
           ]
